/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_management;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author RAGHUNATH DAS
 */
public class DASHBOARD_FINAL_EMPLOYEE extends javax.swing.JFrame {
CardLayout layout;
    /**
     * Creates new form DASHBOARD_FINAL_EMPLOYEE
     */
    public DASHBOARD_FINAL_EMPLOYEE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TIME = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        OPTION = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        stckn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        homer = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        slsn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        bill = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        prdtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        purcn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BODY = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        c_bill = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jLabel135 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jLabel139 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        stock = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        purchase = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        product = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        sales = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TIME.setBackground(new java.awt.Color(32, 64, 81));
        TIME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Time :");
        TIME.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("00:05 am");
        TIME.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, 100, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login Date :");
        TIME.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 15, 120, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("05-02-2021");
        TIME.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 15, 110, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time :");
        TIME.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 60, 50));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("00:05 am");
        TIME.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 100, 50));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date :");
        TIME.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 70, 50));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("05-02-2021");
        TIME.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 120, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minimize.png"))); // NOI18N
        TIME.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, -1, -1));

        jPanel1.add(TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 0, 1090, 73));

        OPTION.setBackground(new java.awt.Color(32, 64, 81));
        OPTION.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welcome");
        OPTION.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 63));

        ID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID : 123456");
        OPTION.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 310, 30));

        Name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name : Raghunath");
        OPTION.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 30));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("VERSION : 1.0.1");
        OPTION.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 320, -1));

        stckn.setBackground(new java.awt.Color(32, 64, 81));
        stckn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stcknMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stock (5).png"))); // NOI18N
        jLabel12.setText(" STOCK");

        javax.swing.GroupLayout stcknLayout = new javax.swing.GroupLayout(stckn);
        stckn.setLayout(stcknLayout);
        stcknLayout.setHorizontalGroup(
            stcknLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stcknLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        stcknLayout.setVerticalGroup(
            stcknLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stcknLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        OPTION.add(stckn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 330, 70));

        homer.setBackground(new java.awt.Color(0, 161, 171));
        homer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homerMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        jLabel13.setText(" HOME");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homerLayout = new javax.swing.GroupLayout(homer);
        homer.setLayout(homerLayout);
        homerLayout.setHorizontalGroup(
            homerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homerLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        homerLayout.setVerticalGroup(
            homerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        OPTION.add(homer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 330, 70));

        slsn.setBackground(new java.awt.Color(32, 64, 81));
        slsn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slsnMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shopping-cart_1.png"))); // NOI18N
        jLabel14.setText(" SALES");

        javax.swing.GroupLayout slsnLayout = new javax.swing.GroupLayout(slsn);
        slsn.setLayout(slsnLayout);
        slsnLayout.setHorizontalGroup(
            slsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slsnLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        slsnLayout.setVerticalGroup(
            slsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slsnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        OPTION.add(slsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 330, 70));

        bill.setBackground(new java.awt.Color(32, 64, 81));
        bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bill (6).png"))); // NOI18N
        jLabel15.setText(" BILL");

        javax.swing.GroupLayout billLayout = new javax.swing.GroupLayout(bill);
        bill.setLayout(billLayout);
        billLayout.setHorizontalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        billLayout.setVerticalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        OPTION.add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 330, 70));

        prdtn.setBackground(new java.awt.Color(32, 64, 81));
        prdtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prdtnMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stack.png"))); // NOI18N
        jLabel16.setText(" PRODUCTS");

        javax.swing.GroupLayout prdtnLayout = new javax.swing.GroupLayout(prdtn);
        prdtn.setLayout(prdtnLayout);
        prdtnLayout.setHorizontalGroup(
            prdtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prdtnLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        prdtnLayout.setVerticalGroup(
            prdtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prdtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        OPTION.add(prdtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 330, 70));

        purcn.setBackground(new java.awt.Color(32, 64, 81));
        purcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purcnMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/packages (5).png"))); // NOI18N
        jLabel17.setText(" PERCHASE");

        javax.swing.GroupLayout purcnLayout = new javax.swing.GroupLayout(purcn);
        purcn.setLayout(purcnLayout);
        purcnLayout.setHorizontalGroup(
            purcnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purcnLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        purcnLayout.setVerticalGroup(
            purcnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purcnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        OPTION.add(purcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 330, 70));

        jPanel7.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Logout");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        OPTION.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 240, 40));

        jPanel1.add(OPTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 752));

        BODY.setBackground(new java.awt.Color(255, 255, 255));
        BODY.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel43.setBackground(new java.awt.Color(180, 242, 225));
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel92.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(32, 64, 81));
        jLabel92.setText("100");
        jPanel43.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 50));

        jLabel93.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Available Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel43.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        home.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 280, 170));

        jPanel44.setBackground(new java.awt.Color(180, 242, 225));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel94.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Today's Sale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel44.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel95.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(32, 64, 81));
        jLabel95.setText("100");
        jPanel44.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 90, 50));

        home.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 280, 170));

        jPanel45.setBackground(new java.awt.Color(180, 242, 225));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel96.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(32, 64, 81));
        jLabel96.setText("100");
        jPanel45.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 50));

        jLabel97.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Pending Work", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel45.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        home.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 280, 170));

        jPanel46.setBackground(new java.awt.Color(180, 242, 225));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel98.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Today's Target", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel46.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel99.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(32, 64, 81));
        jLabel99.setText("100");
        jPanel46.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 50));

        home.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 280, 170));

        jPanel47.setBackground(new java.awt.Color(180, 242, 225));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel100.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(32, 64, 81));
        jLabel100.setText("100");
        jPanel47.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 50));

        jLabel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Grouping Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel47.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        home.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 280, 170));

        jPanel48.setBackground(new java.awt.Color(180, 242, 225));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel102.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Organization", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel48.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        jLabel103.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(32, 64, 81));
        jLabel103.setText("100");
        jPanel48.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 50));

        home.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 280, 170));

        jPanel49.setBackground(new java.awt.Color(180, 242, 225));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel104.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Manage Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel49.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel105.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(32, 64, 81));
        jLabel105.setText("100");
        jPanel49.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 50));

        home.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 280, 170));

        jPanel50.setBackground(new java.awt.Color(180, 242, 225));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel106.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel50.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        jLabel107.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(32, 64, 81));
        jLabel107.setText("100");
        jPanel50.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 50));

        home.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 280, 170));

        jPanel51.setBackground(new java.awt.Color(180, 242, 225));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel108.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Attedence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel51.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel109.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(32, 64, 81));
        jLabel109.setText("100");
        jPanel51.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 50));

        home.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 280, 170));

        BODY.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        c_bill.setBackground(new java.awt.Color(255, 255, 255));
        c_bill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel54.setBackground(new java.awt.Color(180, 242, 225));
        jPanel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel54MouseClicked(evt);
            }
        });
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(32, 64, 81));
        jLabel131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/invoice (11).png"))); // NOI18N
        jPanel54.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, 80));

        jLabel129.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Create Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel54.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 140));

        c_bill.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 280, 170));

        jPanel55.setBackground(new java.awt.Color(180, 242, 225));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel128.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(32, 64, 81));
        jLabel128.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bill (15).png"))); // NOI18N
        jPanel55.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 60, 70));

        jLabel130.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Search Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel55.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 140));

        c_bill.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 280, 170));

        jPanel56.setBackground(new java.awt.Color(180, 242, 225));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel132.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel132.setForeground(new java.awt.Color(32, 64, 81));
        jLabel132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        jPanel56.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 70));

        jLabel133.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Modify Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel56.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, 146));

        c_bill.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 280, 170));

        jPanel57.setBackground(new java.awt.Color(180, 242, 225));
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel135.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(32, 64, 81));
        jLabel135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cash-register.png"))); // NOI18N
        jPanel57.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 70));

        jLabel134.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Delete Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel57.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        c_bill.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 280, 170));

        jPanel58.setBackground(new java.awt.Color(180, 242, 225));
        jPanel58.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel136.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(32, 64, 81));
        jLabel136.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/invoices (11).png"))); // NOI18N
        jPanel58.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 70));

        jLabel137.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Today Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel58.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        c_bill.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 280, 170));

        jPanel59.setBackground(new java.awt.Color(180, 242, 225));
        jPanel59.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel139.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(32, 64, 81));
        jLabel139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bill (16).png"))); // NOI18N
        jPanel59.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 70));

        jLabel138.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "All Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel59.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        c_bill.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 280, 170));

        BODY.add(c_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        stock.setBackground(new java.awt.Color(255, 255, 255));
        stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(180, 242, 225));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(32, 64, 81));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stock (1).png"))); // NOI18N
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 70));

        jLabel39.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Product Stock Check", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        stock.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 280, 170));

        jPanel6.setBackground(new java.awt.Color(180, 242, 225));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(32, 64, 81));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stock-market.png"))); // NOI18N
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 70));

        jLabel40.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "END Stock Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        stock.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 280, 170));

        jPanel19.setBackground(new java.awt.Color(180, 242, 225));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(32, 64, 81));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/oos.png"))); // NOI18N
        jPanel19.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 70));

        jLabel43.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Out of Stock Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel19.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        stock.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 280, 170));

        jPanel20.setBackground(new java.awt.Color(180, 242, 225));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(32, 64, 81));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/box (13).png"))); // NOI18N
        jPanel20.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, 70));

        jLabel44.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Stock Perches Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel20.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        stock.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 280, 170));

        jPanel21.setBackground(new java.awt.Color(180, 242, 225));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(32, 64, 81));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order (1).png"))); // NOI18N
        jPanel21.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 60));

        jLabel47.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Stock Sold Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel21.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        stock.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 280, 170));

        jPanel22.setBackground(new java.awt.Color(180, 242, 225));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel22.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(32, 64, 81));
        jLabel49.setText("100");
        jPanel22.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 50));

        stock.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 280, 170));

        BODY.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        purchase.setBackground(new java.awt.Color(255, 255, 255));
        purchase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(180, 242, 225));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(32, 64, 81));
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shopping-cart (20).png"))); // NOI18N
        jPanel9.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, -1));

        jLabel57.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Purchase Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel9.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        purchase.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 280, 170));

        jPanel10.setBackground(new java.awt.Color(180, 242, 225));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(32, 64, 81));
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cargo.png"))); // NOI18N
        jPanel10.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 70));

        jLabel58.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Purchase Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel10.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        purchase.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 280, 170));

        jPanel26.setBackground(new java.awt.Color(180, 242, 225));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(32, 64, 81));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/note.png"))); // NOI18N
        jPanel26.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 60, 60));

        jLabel61.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Requisition Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel26.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        purchase.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 280, 170));

        jPanel27.setBackground(new java.awt.Color(180, 242, 225));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(32, 64, 81));
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calendar.png"))); // NOI18N
        jPanel27.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, 70));

        jLabel62.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Purchase of a  Month", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel27.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        purchase.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 280, 170));

        jPanel28.setBackground(new java.awt.Color(180, 242, 225));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(32, 64, 81));
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/budget.png"))); // NOI18N
        jPanel28.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 70, 80));

        jLabel65.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Purchase Amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel28.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        purchase.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 280, 170));

        jPanel29.setBackground(new java.awt.Color(180, 242, 225));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(32, 64, 81));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/alarm-clock.png"))); // NOI18N
        jPanel29.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 70, 50));

        jLabel66.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Purchase Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel29.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        purchase.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 280, 170));

        BODY.add(purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        product.setBackground(new java.awt.Color(255, 255, 255));
        product.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel53.setBackground(new java.awt.Color(204, 255, 204));
        jPanel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel53MouseClicked(evt);
            }
        });

        jLabel114.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(0, 204, 102));
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel114.setText("SEARCH PRODUCT");

        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search product.png"))); // NOI18N

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel114, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(jLabel115, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel53Layout.createSequentialGroup()
                .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel114)
                .addContainerGap())
        );

        product.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 210, 170));

        jPanel42.setBackground(new java.awt.Color(204, 255, 204));
        jPanel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel42MouseClicked(evt);
            }
        });

        jLabel110.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(0, 204, 102));
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setText("ADD PRODUCT");

        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ADD PRODUCT 3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel110, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel110)
                .addContainerGap())
        );

        product.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 240, 170));

        jPanel52.setBackground(new java.awt.Color(204, 255, 204));
        jPanel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel52MouseClicked(evt);
            }
        });

        jLabel112.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(0, 204, 102));
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText("SHOW PRODUCT");

        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show product3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel52Layout.createSequentialGroup()
                .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel112)
                .addContainerGap())
        );

        product.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 230, 170));

        jPanel66.setBackground(new java.awt.Color(204, 255, 204));
        jPanel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel66MouseClicked(evt);
            }
        });

        jLabel116.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(0, 204, 102));
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel116.setText("DELETE PRODUCT");

        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel116, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jLabel117, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel66Layout.createSequentialGroup()
                .addComponent(jLabel117, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel116)
                .addContainerGap())
        );

        product.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 220, 160));

        jPanel67.setBackground(new java.awt.Color(204, 255, 204));
        jPanel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel67MouseClicked(evt);
            }
        });

        jLabel118.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(0, 204, 102));
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel118.setText("PRODUCT STOCK ");

        jLabel119.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product stock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel67Layout = new javax.swing.GroupLayout(jPanel67);
        jPanel67.setLayout(jPanel67Layout);
        jPanel67Layout.setHorizontalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel118, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel67Layout.setVerticalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel67Layout.createSequentialGroup()
                .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel118)
                .addContainerGap())
        );

        product.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 210, 160));

        jPanel68.setBackground(new java.awt.Color(204, 255, 204));
        jPanel68.setPreferredSize(new java.awt.Dimension(170, 50));
        jPanel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel68MouseClicked(evt);
            }
        });

        jLabel121.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/management (1).png"))); // NOI18N

        jLabel120.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(0, 204, 102));
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel120.setText(" MANAGE PRODUCT ");

        javax.swing.GroupLayout jPanel68Layout = new javax.swing.GroupLayout(jPanel68);
        jPanel68.setLayout(jPanel68Layout);
        jPanel68Layout.setHorizontalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel120, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(jLabel121, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel68Layout.setVerticalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel68Layout.createSequentialGroup()
                .addComponent(jLabel121, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel120)
                .addContainerGap())
        );

        product.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 240, 170));

        jPanel69.setBackground(new java.awt.Color(204, 255, 204));

        jLabel122.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(0, 204, 102));
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel122.setText("PRODUCT RETUN");

        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product-return.png"))); // NOI18N

        javax.swing.GroupLayout jPanel69Layout = new javax.swing.GroupLayout(jPanel69);
        jPanel69.setLayout(jPanel69Layout);
        jPanel69Layout.setHorizontalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel122, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel69Layout.setVerticalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel69Layout.createSequentialGroup()
                .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel122)
                .addContainerGap())
        );

        product.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 220, 160));

        jPanel70.setBackground(new java.awt.Color(204, 255, 204));

        jLabel124.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(0, 204, 102));
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel124.setText("PRODUCT LOST");

        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/broken-package.png"))); // NOI18N

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel124, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jLabel125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                .addComponent(jLabel125, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel124)
                .addContainerGap())
        );

        product.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 220, 160));

        jPanel71.setBackground(new java.awt.Color(204, 255, 204));
        jPanel71.setPreferredSize(new java.awt.Dimension(170, 50));
        jPanel71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel71MouseClicked(evt);
            }
        });

        jLabel126.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(0, 204, 102));
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText("PRODUCT ID ");

        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product id.png"))); // NOI18N

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel126, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(jLabel127, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel71Layout.createSequentialGroup()
                .addComponent(jLabel127, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel126)
                .addContainerGap())
        );

        product.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 240, 170));

        BODY.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        jPanel5.setBackground(new java.awt.Color(180, 242, 225));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(32, 64, 81));
        jLabel30.setText("100");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 90, 50));

        BODY.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 280, 170));

        jPanel12.setBackground(new java.awt.Color(180, 242, 225));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(32, 64, 81));
        jLabel31.setText("100");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 50));

        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        BODY.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 280, 170));

        jPanel13.setBackground(new java.awt.Color(180, 242, 225));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(32, 64, 81));
        jLabel36.setText("100");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 50));

        BODY.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 280, 170));

        jPanel15.setBackground(new java.awt.Color(180, 242, 225));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(32, 64, 81));
        jLabel21.setText("100");
        jPanel15.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 50));

        jLabel28.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        BODY.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 280, 170));

        jPanel16.setBackground(new java.awt.Color(180, 242, 225));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(32, 64, 81));
        jLabel32.setText("100");
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 50));

        BODY.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 280, 170));

        jPanel17.setBackground(new java.awt.Color(180, 242, 225));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel17.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(32, 64, 81));
        jLabel34.setText("100");
        jPanel17.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 50));

        BODY.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 280, 170));

        jPanel18.setBackground(new java.awt.Color(180, 242, 225));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel18.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 234, 146));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(32, 64, 81));
        jLabel33.setText("100");
        jPanel18.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 50));

        BODY.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 280, 170));

        jPanel14.setBackground(new java.awt.Color(180, 242, 225));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 64, 81), 2), "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(32, 64, 81))); // NOI18N
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 146));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(32, 64, 81));
        jLabel35.setText("100");
        jPanel14.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 50));

        BODY.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 280, 170));

        javax.swing.GroupLayout salesLayout = new javax.swing.GroupLayout(sales);
        sales.setLayout(salesLayout);
        salesLayout.setHorizontalGroup(
            salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        salesLayout.setVerticalGroup(
            salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        BODY.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        jPanel1.add(BODY, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 73, 1074, 679));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1410, 752));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homerMouseClicked
        // TODO add your handling code here:
          home.setVisible(true);
        homer.setBackground(Color.decode("00A1AB"));
        product.setVisible(false);
        prdtn.setBackground(Color.decode("#204051"));
        stock.setVisible(false);
        stckn.setBackground(Color.decode("#204051"));
        purchase.setVisible(false);
        purcn.setBackground(Color.decode("#204051"));
        sales.setVisible(false);
        slsn.setBackground(Color.decode("#204051"));
        c_bill.setVisible(false);
        bill.setBackground(Color.decode("#204051"));
       
    }//GEN-LAST:event_homerMouseClicked

    private void prdtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prdtnMouseClicked
        // TODO add your handling code here:
          home.setVisible(false);
        homer.setBackground(Color.decode("#204051"));
        product.setVisible(true);
        prdtn.setBackground(Color.decode("#00A1AB"));
        stock.setVisible(false);
        stckn.setBackground(Color.decode("#204051"));
        purchase.setVisible(false);
        purcn.setBackground(Color.decode("#204051"));
        sales.setVisible(false);
        slsn.setBackground(Color.decode("#204051"));
         c_bill.setVisible(false);
        bill.setBackground(Color.decode("#204051"));
    }//GEN-LAST:event_prdtnMouseClicked

    private void purcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purcnMouseClicked
        // TODO add your handling code here:
          home.setVisible(false);
        homer.setBackground(Color.decode("#204051"));
        product.setVisible(false);
        prdtn.setBackground(Color.decode("#204051"));
        stock.setVisible(false);
        stckn.setBackground(Color.decode("#204051"));
        purchase.setVisible(true);
        purcn.setBackground(Color.decode("#00A1AB"));
        sales.setVisible(false);
        slsn.setBackground(Color.decode("#204051"));
         c_bill.setVisible(false);
        bill.setBackground(Color.decode("#204051"));
    }//GEN-LAST:event_purcnMouseClicked

    private void stcknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stcknMouseClicked
        // TODO add your handling code here:
         home.setVisible(false);
        homer.setBackground(Color.decode("#204051"));
        product.setVisible(false);
        prdtn.setBackground(Color.decode("#204051"));
        stock.setVisible(true);
        stckn.setBackground(Color.decode("#00A1AB"));
        purchase.setVisible(false);
        purcn.setBackground(Color.decode("#204051"));
        sales.setVisible(false);
        slsn.setBackground(Color.decode("#204051"));
         c_bill.setVisible(false);
        bill.setBackground(Color.decode("#204051"));
    }//GEN-LAST:event_stcknMouseClicked

    private void slsnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slsnMouseClicked
        // TODO add your handling code here:
        home.setVisible(false);
        homer.setBackground(Color.decode("#204051"));
        product.setVisible(false);
        prdtn.setBackground(Color.decode("#204051"));
        stock.setVisible(false);
        stckn.setBackground(Color.decode("#204051"));
        purchase.setVisible(false);
        purcn.setBackground(Color.decode("#204051"));
        sales.setVisible(true);
        slsn.setBackground(Color.decode("#00A1AB"));
         c_bill.setVisible(false);
        bill.setBackground(Color.decode("#204051"));
    }//GEN-LAST:event_slsnMouseClicked

    private void billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMouseClicked
        // TODO add your handling code here:
         home.setVisible(false);
        homer.setBackground(Color.decode("#204051"));
        product.setVisible(false);
        prdtn.setBackground(Color.decode("#204051"));
        stock.setVisible(false);
        stckn.setBackground(Color.decode("#204051"));
        purchase.setVisible(false);
        purcn.setBackground(Color.decode("#204051"));
        sales.setVisible(false);
        slsn.setBackground(Color.decode("#204051"));
         c_bill.setVisible(true);
        bill.setBackground(Color.decode("#00A1AB"));
    }//GEN-LAST:event_billMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel42MouseClicked
        // TODO add your handling code here:
        ADD_NEW_PRODUCT anp = new ADD_NEW_PRODUCT();
        anp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel42MouseClicked

    private void jPanel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel52MouseClicked
        // TODO add your handling code here:
        PRODUCT_DETAILS_EMPLOYEE pde = new PRODUCT_DETAILS_EMPLOYEE();
        pde.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel52MouseClicked

    private void jPanel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel53MouseClicked
        // TODO add your handling code here:
        SEARCH_PRODUCT sp = new SEARCH_PRODUCT();
       sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel53MouseClicked

    private void jPanel71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel71MouseClicked
        // TODO add your handling code here:
        SEARCH_PRODUCT sp = new SEARCH_PRODUCT();
       sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel71MouseClicked

    private void jPanel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel66MouseClicked
        // TODO add your handling code here:
        DELETE_PRODUCT dp = new DELETE_PRODUCT();
       dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel66MouseClicked

    private void jPanel67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel67MouseClicked
        // TODO add your handling code here:
         PRODUCT_STOCK_CHECK psc = new PRODUCT_STOCK_CHECK();
       psc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel67MouseClicked

    private void jPanel68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel68MouseClicked
        // TODO add your handling code here:
        MANAGE_ORDER_EMP moe = new MANAGE_ORDER_EMP();
       moe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel68MouseClicked

    private void jPanel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel54MouseClicked
        // TODO add your handling code here:
        BILL_PRINT bp = new BILL_PRINT();
        bp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel54MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    PRODUCT_STOCK_CHECK psc = new PRODUCT_STOCK_CHECK();
        psc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
       END_STOCK_REPORT esr = new END_STOCK_REPORT();
        esr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD_FINAL_EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD_FINAL_EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD_FINAL_EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD_FINAL_EMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD_FINAL_EMPLOYEE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BODY;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel OPTION;
    private javax.swing.JPanel TIME;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel bill;
    private javax.swing.JPanel c_bill;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel prdtn;
    private javax.swing.JPanel product;
    private javax.swing.JPanel purchase;
    private javax.swing.JPanel purcn;
    private javax.swing.JPanel sales;
    private javax.swing.JPanel slsn;
    private javax.swing.JPanel stckn;
    private javax.swing.JPanel stock;
    // End of variables declaration//GEN-END:variables
}
