/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author RAGHUNATH DAS
 */
public class MANAGER_UPDATE_PROFILE extends javax.swing.JFrame {
     String First_name = null;
    String Last_name = null;
    String Phone = null;
    String Email = null;
    String DOB = null;
    String Gender= null;
    String Address =null;
    String date=null;
    String time = null;
    

    /**
     * Creates new form MANAGER_UPDATE_PROFILE
     */
    public MANAGER_UPDATE_PROFILE() {
        initComponents();
    }
    void udpe (String fullname, String mng_Id,String email,String t1,String d1,String p) {
      //  Name = fullname;
        //ID = mng_Id;
        Email = email;
        time = t1;
        date = d1;
        Phone= p;
       // first_name.setEditable(false);
         //first_name.setText(Name);
       /* void nupe  (String fname, String lname,String ph,String email,String dob,String gender,String address) {
        First_name = fname;
        Last_name = lname;
        Phone = ph;
        Email = email;
        DOB = dob;
        Gender= gender;
        Address = address;
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Searchb = new javax.swing.JButton();
        Search1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lname.setBackground(new java.awt.Color(255, 255, 255));
        lname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 99, 450, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 69, 130, 20));

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 369, 920, 100));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("DOB");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 245, -1, -1));

        ph.setBackground(new java.awt.Color(255, 255, 255));
        ph.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ph.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 187, 420, 40));

        fname.setBackground(new java.awt.Color(255, 255, 255));
        fname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 99, 420, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 157, -1, -1));

        dob.setBackground(new java.awt.Color(255, 255, 255));
        dob.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 271, 420, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 69, -1, -1));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 187, 450, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button (13).png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 497, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button (11).png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 497, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Gender");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 245, -1, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Phone");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 157, -1, -1));

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 0));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Femail", "Others" }));
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 275, 450, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Home Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 333, 170, 30));

        Searchb.setBackground(new java.awt.Color(0, 51, 255));
        Searchb.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Searchb.setForeground(new java.awt.Color(255, 255, 255));
        Searchb.setText("Search");
        Searchb.setBorder(null);
        Searchb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchbMouseClicked(evt);
            }
        });
        jPanel2.add(Searchb, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 125, 45));

        Search1.setBackground(new java.awt.Color(255, 255, 255));
        Search1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Search1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 470, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/RaghuSearch.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 500, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 560));

        jPanel3.setBackground(new java.awt.Color(32, 64, 81));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Profile");

        jButton1.setBackground(new java.awt.Color(32, 64, 81));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel16MouseClicked

    private void SearchbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbMouseClicked
        // TODO add your handling code here:
      String product_idee = Search1.getText();
    String product_ideoo= null;
        try {
        
             //Data fetch from database
            String sql = "Select * from add_new_product Where Product_id = ?";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
             
            ps.setString(1,product_idee);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                product_ideoo =rs.getString("Product_id");
                 System.out.println("EMpppppp "+product_ideoo);
                String product_nameyy =rs.getString("Product_name");
                 System.out.println("pppnnn "+product_nameyy);
                String description =rs.getString("Description");
                 System.out.println("ddsss "+description);
                String standerd_cost =rs.getString("Standerd_cost");
                 System.out.println("ssccc "+standerd_cost);
                String unitprice =rs.getString("Unit_price");
                 System.out.println("uuppp "+unitprice);
                String mfgdate =rs.getString("Mfg_date");
                 System.out.println("mmmddd "+mfgdate);
                String expirydate =rs.getString("Exp_date");
                 System.out.println("eeeddd "+expirydate);
                String quantity =rs.getString("Quantity");
                 System.out.println("qqqqnnn "+quantity);
                String category =rs.getString("Category");
                 System.out.println("ccccttt "+category);
                String brand =rs.getString("Brand");
                System.out.println("bbbrr "+brand);
               // JOptionPane.showMessageDialog(this, "Product Found");
                
               
                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(this, "Enter Correct Product Id");
                System.out.println("Enter Correct Product Id");
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }
        try{
            //ganesh
            if(ADD_NEW_PRODUCT_DETAOBJ.validate(product_idee))
                 

            {System.out.println("ppppppppppiiiiiiiiiii"+product_idee);
                JOptionPane.showMessageDialog(this, "product found");
               // System.out.println("pppppppppp"+pro1_id);
             //  String table[] =  {Product_id};
              
         // DefaultTableModel model = (DefaultTableModel)table.getModel();
           // model.addRow(table);
              
       //     fname.setText(rs.getString("FIRST_NAME"));
    
            //raghu
            }else 
            JOptionPane.showMessageDialog(this, "product not found");
            //sudip
            
            
        }catch (Exception e){
            System.out.println("Exception -"+e);  
    }                                    
     
           
      
    
    

    }//GEN-LAST:event_SearchbMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           DASHBOARD_M dm = new DASHBOARD_M();
    dm.mngname(First_name,Last_name,Email,Phone,date,time);
    dm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGER_UPDATE_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGER_UPDATE_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGER_UPDATE_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGER_UPDATE_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGER_UPDATE_PROFILE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search1;
    private javax.swing.JButton Searchb;
    private javax.swing.JTextField address;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField ph;
    // End of variables declaration//GEN-END:variables
}
