/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author RAGHUNATH DAS
 */
public class UPDATEPROFILE_EMP extends javax.swing.JFrame {
            
    String mng_Id = null;
    String emp_Id = null;
    String Name = null;
    String Phone = null;
    String Email = null;
    String ID = null;
    String date=null;
    String time = null;
    
    
    /**
     * Creates new form UPDATEPROFILE
     */
    public UPDATEPROFILE_EMP() {
       initComponents();
       
    }

      void udpe (String fullname, String mng_Id,String email,String t1,String d1,String p) {
        Name = fullname;
        ID = mng_Id;
        Email = email;
        time = t1;
        date = d1;
        Phone= p;
        first_name.setEditable(false);
         first_name.setText(Name);
        //first_name.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_addr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        c_phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        c_dob = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        c_gen = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close (1).png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 20, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 208, 221));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update Profile");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 1400, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        first_name.setBackground(new java.awt.Color(255, 255, 255));
        first_name.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        first_name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 420, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 130, 20));

        last_name.setBackground(new java.awt.Color(255, 255, 255));
        last_name.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        last_name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 450, 40));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Home Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 170, 30));

        c_addr.setBackground(new java.awt.Color(255, 255, 255));
        c_addr.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        c_addr.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(c_addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 920, 100));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        c_email.setBackground(new java.awt.Color(255, 255, 255));
        c_email.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        c_email.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(c_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 450, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        c_phone.setBackground(new java.awt.Color(255, 255, 255));
        c_phone.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        c_phone.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(c_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 420, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DOB");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        c_dob.setBackground(new java.awt.Color(255, 255, 255));
        c_dob.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        c_dob.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(c_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 420, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gender");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, 30));

        c_gen.setBackground(new java.awt.Color(255, 255, 255));
        c_gen.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        c_gen.setForeground(new java.awt.Color(0, 0, 0));
        c_gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Femail", "Others" }));
        jPanel1.add(c_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 450, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button (11).png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button (13).png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/raghu2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1400, 787));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  void Update_Profile(){
         System.out.println("!!!!!!!!56!");
         String firstname= first_name.getText();
        
         try{   
            String sql = "Select * from employee_register Where FIRST_NAME = ?";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,firstname);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String eml=rs.getString("EMAIL");
                String mob=rs.getString("MOBILE_NO"); 
                String db=rs.getString("DOB");
                String gn=rs.getString("GENDER");
                String add =rs.getString("ADDRESS");
                c_email.setText(eml);
                c_phone.setText(mob);
                c_dob.setText(db);
                c_gen.setSelectedItem(gn);
                c_addr.setText(add);
                
                
                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(null, "NOTHING FOUND IN DATABASE!!!!!!");
            }
            con.close();
           }
        catch(Exception e){System.out.println(e);}
         
  }
    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
          DASHBOARD_M dm = new DASHBOARD_M();
    dm.mngname(Name,ID,Email,Phone,date,time);
    dm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        String FST = first_name.getText();    
        String DOB = c_dob.getText();      
        String add = c_addr.getText();
        String gen2 = c_gen.getSelectedItem().toString();
        System.out.println("@@@@@@@@@ "+gen2);
        
        
        
        int i = UPDATEPROFILE_M_DATAOBJECT.updateprofile_m(DOB,add,gen2,ID);
            //(FIRST_NAME,LAST_NAME,EMAIL,MOBILE_NO,PASSWORD,CONFIRM_PASSWORD,ADDRESS,GENDER)
           if(i>0){
                System.out.println("Data inserted");
                JOptionPane.showMessageDialog(this, "Your Profile Update Sucessfully "); 
                new REGISTRATION().setVisible(true);
                this.dispose();
           }else{
                System.out.println("Data NOT inserted");
                JOptionPane.showMessageDialog(this, "Your Profile Not Update Sucessfully"); 
           }
                                   
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATEPROFILE_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATEPROFILE_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATEPROFILE_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATEPROFILE_EMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEPROFILE_EMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_addr;
    private javax.swing.JTextField c_dob;
    private javax.swing.JTextField c_email;
    private javax.swing.JComboBox<String> c_gen;
    private javax.swing.JTextField c_phone;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField last_name;
    // End of variables declaration//GEN-END:variables
}
